In [2]:
import sys
sys.version

'2.7.15 (default, Jun 17 2018, 12:51:03) \n[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]'

In [3]:
import numpy as np
np.__version__

'1.15.1'

In [11]:
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim, a.shape, a.size, a.dtype)
a *= 2
print(a)

(2, (2, 3), 6, dtype('int64'))
[[ 2  4  6]
 [ 8 10 12]]


In [18]:
shape = (3, 4)
print(np.zeros(shape))
print(3*np.ones(shape))
print(4*np.eye(3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]
